//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPerfumery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfumeries
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public decimal Cost { get; set; }
        public int Discount { get; set; }
        public int Count { get; set; }
        public string Photo { get; set; }
    
        public virtual Categoties Categoties { get; set; }
    }
}
